- hosts: all
  tasks:
    - name: symlink
      command: "cp -f plugins/image-diff/package.json plugins/package.json"
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/{{ zuul.projects["gerrit.googlesource.com/gerrit"].src_dir }}'
