- hosts: all
  tasks:
    - name: symlink
      shell: |
        ln --symbolic --force plugins/image-diff/external_package.json plugins/package.json
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/{{ zuul.projects["gerrit.googlesource.com/gerrit"].src_dir }}'
